# -*- coding: utf-8 -*-
"""What a client update changed, for the client before the first snapshot this mod took (client_snapshot.ClientSnapshot.other).

Only paths in the snapshot's scope, never a CRC or a byte of the client. The battles recorded by such a client are repaired
by it: a path listed here counts as changed (its CRC unknown), every other in-scope path as the later client has it.

2.4.0.1 #950 -> 2.4.0.2 #964 (01.10.2026): decoded from the client's own patch deltas in updates/*.wgpkg (WGC 5460, 5470;
outputs/rebuild-research-client-2026-10-02.md section 2: 54 members of scripts.pkg; no member under scripts/ of an event
package, no collision .havok, no vehicle prefab) and the locale package (17 texts). Members the patch removed are not seen
by that method (unknown). A one-off list (02.10): the next updates are seen by the mod's own snapshots; a tool that makes
such a list from updates/ at build time is a separate item (BACKLOG 55).
"""
CHANGES = (
    {'from': 'v.2.4.0.1 #950', 'to': 'v.2.4.0.2 #964', 'changed': (
        'res/text/lc_messages/achievements.mo',
        'res/text/lc_messages/battle_pass.mo',
        'res/text/lc_messages/china_crew.mo',
        'res/text/lc_messages/czech_crew.mo',
        'res/text/lc_messages/france_crew.mo',
        'res/text/lc_messages/gb_crew.mo',
        'res/text/lc_messages/germany_crew.mo',
        'res/text/lc_messages/italy_crew.mo',
        'res/text/lc_messages/japan_crew.mo',
        'res/text/lc_messages/lore.mo',
        'res/text/lc_messages/poland_crew.mo',
        'res/text/lc_messages/sweden_crew.mo',
        'res/text/lc_messages/tooltips.mo',
        'res/text/lc_messages/usa_crew.mo',
        'res/text/lc_messages/ussr_crew.mo',
        'res/text/lc_messages/ussr_crew_en.mo',
        'res/text/lc_messages/vehicle_customization.mo',
        'scripts/client/gui/Scaleform/locale/BATTLE_PASS.pyc',
        'scripts/client/gui/Scaleform/locale/RES_ICONS.pyc',
        'scripts/client/gui/Scaleform/locale/TOOLTIPS.pyc',
        'scripts/client/gui/Scaleform/locale/VEHICLE_CUSTOMIZATION.pyc',
        'scripts/client/gui/battle_pass/battle_pass_buyer.pyc',
        'scripts/client/gui/impl/gen/resources/aliases.pyc',
        'scripts/client/gui/impl/gen/resources/animations.pyc',
        'scripts/client/gui/impl/gen/resources/atlases.pyc',
        'scripts/client/gui/impl/gen/resources/dynamic_ids.pyc',
        'scripts/client/gui/impl/gen/resources/images.pyc',
        'scripts/client/gui/impl/gen/resources/sounds.pyc',
        'scripts/client/gui/impl/gen/resources/strings.pyc',
        'scripts/client/gui/impl/gen/resources/styles.pyc',
        'scripts/client/gui/impl/gen/resources/videos.pyc',
        'scripts/client/gui/impl/gen/view_models/views/lobby/battle_pass/battle_pass_buy_level_view_model.pyc',
        'scripts/client/gui/impl/lobby/battle_pass/battle_pass_buy_levels_view.pyc',
        'scripts/client/gui/shared/gui_items/dossier/factories.pyc',
        'scripts/client/visual_script_client/cgf_blocks.pyc',
        'scripts/common/dossiers2/custom/account_layout.pyc',
        'scripts/common/dossiers2/custom/records.pyc',
        'scripts/common/items/components/tankmen_components.pyc',
        'scripts/entity_defs/interfaces/AccountVersion.def',
        'scripts/item_defs/achievements.xml',
        'scripts/item_defs/customization/attachments/3d_attachments.xml',
        'scripts/item_defs/customization/attachments/attachments.xml',
        'scripts/item_defs/customization/attachments/list.xml',
        'scripts/item_defs/customization/camouflages/list.xml',
        'scripts/item_defs/customization/camouflages/unified.xml',
        'scripts/item_defs/customization/decals/inscriptions_special.xml',
        'scripts/item_defs/customization/decals/list.xml',
        'scripts/item_defs/customization/insignias/custom_insignias.xml',
        'scripts/item_defs/customization/insignias/list.xml',
        'scripts/item_defs/customization/paints/custom_paints.xml',
        'scripts/item_defs/customization/paints/list.xml',
        'scripts/item_defs/customization/projection_decals/list.xml',
        'scripts/item_defs/customization/projection_decals/projection_decals.xml',
        'scripts/item_defs/customization/styles/list.xml',
        'scripts/item_defs/customization/styles/uk.xml',
        'scripts/item_defs/customization/styles/unified.xml',
        'scripts/item_defs/special_voices.xml',
        'scripts/item_defs/tankmen/china.xml',
        'scripts/item_defs/tankmen/common/lore.xml',
        'scripts/item_defs/tankmen/czech.xml',
        'scripts/item_defs/tankmen/france.xml',
        'scripts/item_defs/tankmen/germany.xml',
        'scripts/item_defs/tankmen/italy.xml',
        'scripts/item_defs/tankmen/japan.xml',
        'scripts/item_defs/tankmen/poland.xml',
        'scripts/item_defs/tankmen/sweden.xml',
        'scripts/item_defs/tankmen/uk.xml',
        'scripts/item_defs/tankmen/usa.xml',
        'scripts/item_defs/tankmen/ussr.xml',
        'scripts/item_defs/vehicles/uk/GB130_FV225_Collector.xml',
        'scripts/item_defs/vehicles/uk/GB130_FV225_Collector_siege_mode.xml')},
)
