"""The client's code and data the characteristics and the vehicle files are built from - made for each client the mod is built
for (BACKLOG 55, 02.10), beside tools/client_version.py:

    python tools/client_code_set.py            run the offline stand over the whole catalogue, write
                                               mod/local_armor_inspector/client_code.py

The stand is tests/fixtures-local/ttx-offline (local, never committed: the client's own python27.dll and items.vehicles over
its packages, read-only). tools/client_code_set27.py builds every type there and records what the builds execute, what that
code names, what files the client's code opens and which text domains it asks. The output holds names only.

Why (the user, 02.10): when a formula changes, check the formula, not every value run through it. A characteristics or
vehicle file is current while its own data (its key) and the client's code its build EXECUTES did not change; the crew's
tables that 2.4.0.2 changed (tankmen_components.pyc) are executed by no build - such an update rebuilds nothing.
"""
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STAND = ROOT / 'tests' / 'fixtures-local' / 'ttx-offline'
TARGET = ROOT / 'mod' / 'local_armor_inspector' / 'client_code.py'
# The stand's output of every type, per client (hashes only): the next client's build compares against it (STAND_CHANGED).
OUTPUTS = ROOT / 'tests' / 'golden' / 'stand-outputs.json'
sys.path.insert(0, str(ROOT / 'tools'))
from client_version import VERSION_XML  # noqa: E402


def collect():
    if not (STAND / 'run27.py').is_file():
        raise SystemExit('No offline stand at %s (tests/fixtures-local is local: make it on the machine with the client)' % STAND)
    out = Path(tempfile.mkdtemp()) / 'code_set.json'
    subprocess.run([sys.executable, str(STAND / 'run27.py'), str(ROOT / 'tools' / 'client_code_set27.py'), str(out)],
                   check=True, cwd=str(STAND), env=dict(os.environ, BULLBA_REPO=str(ROOT)))
    value = json.loads(out.read_text(encoding='utf-8'))
    if value.get('crash'): raise SystemExit('The stand failed:\n' + value['crash'])
    if value.get('errors'): raise SystemExit('%d builds failed on the stand, first: %s' % (len(value['errors']), value['errors'][0]))
    return value


def shared(paths):
    """The data files every type is built with: what items reads at its start and what the builds open beyond a vehicle's
    own XML and its nation's files (those are keyed per type)."""
    found = set()
    for path in paths:
        parts = path.split('/')
        if path.startswith('scripts/item_defs/vehicles/') and len(parts) > 4 and parts[3] != 'common': continue
        found.add(path)
    return sorted(found)


def stand_changes(value, label):
    """(the previous client, the types whose stand output differs from it) - and the stored hashes updated with this client's
    (the last two clients kept). The stubs of the stand are the same on both sides, so what the stand sees change is caught
    whatever made it: the code, the data, a table built at import (BACKLOG 55, second review C2)."""
    stored = json.loads(OUTPUTS.read_text(encoding='utf-8')) if OUTPUTS.is_file() else {'note': 'hashes only', 'clients': {}}
    clients = stored['clients']
    previous = [c for c in clients if c != label]
    since = sorted(previous, key=lambda c: clients[c].get('order', 0))[-1] if previous else None
    changed = []
    if since is not None:
        before = clients[since]['types']
        changed = sorted(t for t, h in value['outputs'].items() if t in before and before[t] != h)
    order = max([c.get('order', 0) for c in clients.values()] or [0]) + (0 if label in clients else 1)
    clients[label] = {'order': clients.get(label, {}).get('order', order), 'types': value['outputs']}
    for old in sorted(clients, key=lambda c: clients[c]['order'])[:-2]: del clients[old]
    OUTPUTS.write_text(json.dumps(stored, indent=1, sort_keys=True) + '\n', encoding='utf-8', newline='\n')
    return since, changed


def render(value):
    label = value['versionXml'].split('<version>', 1)[1].split('</version>', 1)[0].strip()
    if label != VERSION_XML:
        raise SystemExit('The stand reads client %s, tools/client_version.py says %s' % (label, VERSION_XML))
    code = sorted(set(value['executed']) | set(value['referenced']))
    since, changed = stand_changes(value, label)
    lines = ['# -*- coding: utf-8 -*-',
             '"""THE CLIENT\'S CODE AND DATA THE CHARACTERISTICS AND VEHICLE FILES ARE BUILT FROM (BACKLOG 55) - generated by',
             'tools/client_code_set.py on the offline stand for client %s: %d types built, %d client modules executed by the' % (label, value['types'], len(value['executed'])),
             'builds and %d more whose objects that code names. Names only. Do not edit: run the tool for a new client."""' % len(value['referenced']),
             'CLIENT = %r' % label,
             '# The modules (scripts.pkg paths) whose code identity is the "formula" of every characteristics and vehicle file.',
             'CODE_MODULES = (']
    lines += ['    %r,' % p for p in code] + [')',
              '# The data files read for every type alike (items\' start and the builds, beyond a type\'s own XML and its nation\'s).',
              'SHARED_DATA = (']
    lines += ['    %r,' % p for p in shared(value['openedBoot'] + value['openedBuild'])] + [')',
              '# The text domains (res/text/lc_messages/<domain>.mo) the builds ask translations from.',
              'TEXT_DOMAINS = (']
    lines += ['    %r,' % d for d in value['domains']] + [')',
              '# The types whose output on the stand differs from client %s\'s (tests/golden/stand-outputs.json): rebuilt once.' % since,
              'STAND_CLIENT = %r' % label, 'STAND_SINCE = %r' % since, 'STAND_CHANGED = (']
    lines += ['    %r,' % t for t in changed] + [')', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    TARGET.write_text(render(collect()), encoding='utf-8', newline='\n')
    print('wrote', TARGET)
